dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.4.2
  - OpenZeppelin/openzeppelin-contracts@4.7.3
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.2'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.3'
dotenv: .env
networks:
  default: development
  development:
    link_token: '0x01BE23585060835E02B77ef475b0Cc51aA1e0709'
    keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    callback_gas_limit: 100000
    request_confirmations: 3
    verify: False
  mainnet-fork:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  rinkeby:
    vrf_coordinator: '0x6168499c0cffcacd319c818142124b7a15e857ab'
    eth_usd_price_feed: '0x01be23585060835e02b77ef475b0cc51aa1e0709'
    link_token: '0x01BE23585060835E02B77ef475b0Cc51aA1e0709'
    keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    callback_gas_limit: 100000
    request_confirmations: 3
    verify: True
  goerli:
    vrf_coordinator: '0x2Ca8E0C643bDe4C2E08ab1fA0da3401AdAD7734D'
    link_token: '0x326C977E6efc84E512bB9C30f76E30c160eD06FB'
    keyHash: '0x79d3d8832d904592c0bf9818b621522c988bb8b0c05cdc3b15aea1b6e8db0c15'
    callback_gas_limit: 100000
    request_confirmations: 3
    verify: True
wallets:
  from_key: ${PRIVATE_KEY}